WebCafe/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebCafe.Models;

namespace WebCafe.Controllers
{
    public class GioHangController : Controller
    {
        QuanLyCaPheEntities db = new QuanLyCaPheEntities();
        private double giaTri;
        int i = 0;
        // GET: GioHang
        public ActionResult Index()
        {
            if(giaTri != null)
            {
                ViewBag.GiaTri = giaTri;
            }
            return View((List<CartModel>)Session["cart"]);
        }

        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { SanPham = db.SanPhams.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { SanPham = db.SanPhams.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        public ActionResult UpdateCart(List<int> id,List<int> quantity)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for(int i = 0; i < id.Count; i ++)
            {
                if(id[i] == cart[i].SanPham.MaSP)
                {
                    cart[i].Quantity = quantity[i];
                }
            }
            Session["cart"] = cart;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].SanPham.MaSP.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.SanPham.MaSP == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        public ActionResult AddCoupon(string Ma)
        {
            List<WebCafe.Models.GiamGia> giamGias = db.GiamGias.Where(x => x.active == true).ToList();
            if(Session["TaiKhoanTV"] != null)
            {
                foreach (GiamGia item in giamGias)
                {
                    if(item.MaGiamGia == Ma)
                    {
                        giaTri = (double)item.GiaTri;
                        Session["MaGiamGia"] = (string)item.MaGiamGia;
                        Session["GiaTri"] = (double)item.GiaTri;

                        return Json(new {GiaTri = giaTri , Message = "Thêm mã giảm giá hành công", JsonRequestBehavior.AllowGet });
                    }
                    else
                    {
                        return Json(new { GiaTri = 0, Message = "Mã giảm giá không hợp lệ", JsonRequestBehavior.DenyGet });
                    }
                }
            }
            else
            {
                return Json(new { GiaTri = 0, Message = "Bạn chưa đăng nhập", JsonRequestBehavior.DenyGet });
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        public ActionResult ThanhToan()
        {
            return View((List<CartModel>)Session["cart"]);
        }

        public ActionResult InfoAccount(string MaTV)
        {
            WebCafe.Models.ThanhVien thanhViens = db.ThanhViens.Where(x => x.TaiKhoan == MaTV).FirstOrDefault();
            if(thanhViens != null)
            {
                return Json(new { TaiKhoan = thanhViens.TaiKhoan,HoTen = thanhViens.HoTen,DiaChi = thanhViens.DiaChi,Email = thanhViens.Email,DienThoai = thanhViens.DienThoai, JsonRequestBehavior.AllowGet });
            }
            else
            {
                return Json(new { Message = "Bạn chưa đăng nhập!!!!", JsonRequestBehavior.AllowGet });
            }
        }
    }
}

WebCafe/Views/GioHang/Index.cshtml
@model IEnumerable<WebCafe.Models.CartModel>

@{
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Giỏ hàng</strong></div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <form method="post">
                <div class="row mb-5">
                    <div class="site-blocks-table col-md-12">
                        <table class="table table-bordered ">
                            <thead>
                                <tr>
                                    <th class="product-thumbnail">Hình ảnh</th>
                                    <th class="product-name">Tên sản phẩm</th>
                                    <th class="product-price">Đơn giá</th>
                                    <th class="product-quantity">Số lượng</th>
                                    <th class="product-total">Tổng tiền</th>
                                    <th class="product-remove">Xóa</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr id="product-@item.SanPham.MaSP">
                                            <td class="product-thumbnail">
                                                <img src="~/Upload/sanpham/@item.SanPham.HinhAnh" alt="Image" class="img-fluid">
                                            </td>
                                            <td class="product-name">
                                                <h2 class="h5 text-black">@item.SanPham.TenSP</h2>
                                            </td>
                                            <td>@String.Format("{0:0,0 vnđ}", item.SanPham.DonGia)</td>
                                            <td>
                                                <div class="input-group mb-3" style="max-width: 120px;">
                                                    <div class="input-group-prepend">
                                                        <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                                                    </div>
                                                    <input type="text" class="form-control text-center data-quantity" value="@item.Quantity" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                                                    </div>
                                                </div>

                                            </td>
                                            <td>
                                                @{
                                                    double gia = (double)item.SanPham.DonGia;
                                                    int soLuong = item.Quantity;
                                                    double result = gia * soLuong;
                                                    <Span id="tongTienSP"> @String.Format("{0:0,0 vnđ}", result) </Span>

                                                }
                                            </td>

                                            <td>
                                                <input type="hidden" value="@item.SanPham.MaSP" class="data-id" id="productid" />
                                                <a href="" id="removecart" class="btn btn-warning btn-sm">X</a>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <p>Không có sản phẩm trong giỏ hàng</p>
                                }
                            </tbody>
                        </table>
                    </div>
                    @*</form>*@
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="row mb-5">
                            <div class="col-md-6 mb-3 mb-md-0">
                                <a class="btn btn-warning btn-sm btn-block" style="color:black;" id="updatecart">Cập nhật giỏ hàng</a>
                            </div>
                            <div class="col-md-6">
                                <a href="@Url.Action("Index", "SanPham")" class="btn btn-outline-warning btn-sm btn-block">Tiếp tục mua sắm</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label class="text-black h4" for="coupon">Giảm giá</label>
                                <p>Nhập mã phiếu giảm giá của bạn nếu bạn có.</p>
                            </div>
                            <div class="col-md-8 mb-3 mb-md-0">
                                <input type="text" class="form-control py-3" id="MaGiamGia" name="MaGiamGia" placeholder="Mã giảm giá">
                            </div>
                            <div class="col-md-4">
                                <button class="btn btn-warning btn-sm" id="coupon">Áp dụng phiếu giảm giá</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 pl-5">
                        <div class="row justify-content-end">
                            <div class="col-md-7">
                                <div class="row">
                                    <div class="col-md-12 text-right border-bottom mb-5">
                                        <h3 class="text-black h4 text-uppercase">Tổng cộng</h3>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <span class="text-black">Giá tiền</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        @{double tongTienThanhToan = 0; }
                                        @if (Model != null)
                                        {
                                            foreach (var item in Model)
                                            {
                                                if (item.SanPham.DonGia != null)
                                                {
                                                    double gia = (double)item.SanPham.DonGia;
                                                    int soLuong = item.Quantity;
                                                    double result = gia * soLuong;
                                                    tongTienThanhToan += result;
                                                }

                                            }
                                        }
                                        <strong class="text-black">@String.Format("{0:0,0 vnđ}", tongTienThanhToan)</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <span class="text-black">Giảm giá</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <strong class="text-danger" id="tienGiamGia"></strong>
                                    </div>
                                </div>
                                <div class="row mb-5">
                                    <div class="col-md-6">
                                        <span class="text-black">Tổng tiền</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <strong class="text-success" id="tienTong">@String.Format("{0:0,0 vnđ}", tongTienThanhToan)</strong>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <a class="btn btn-warning btn-lg py-3 btn-block" style="color:black;" href="@Url.Action("ThanhToan", "GioHang")" type="submit">Tiến hành thanh toán</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section ClientScript{

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "GioHang")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });

        $("#updatecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            //var Quantitys = window.document.getElementsByClassName("data-quantity");
            var Quantitys = $(".data-quantity");
            var aDataQuantity = [];
            for (var i = 0; i < Quantitys.length; i++) {
                aDataQuantity.push(Quantitys[i].value);
            }
            console.log(aDataQuantity);
            //var ids = window.document.getElementsByClassName("data-id");
            var ids = $(".data-id");

            var aDataId = [];
            for (var i = 0; i < ids.length; i++) {
                aDataId.push(ids[i].value);
            }
            console.log(aDataId);
            model.id = aDataId;
            model.quantity = aDataQuantity;
            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateCart", "GioHang")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    alert("Cập nhật giỏ hàng thành công!");
                    $('#tongTienSP').text();
                    location.reload();
                }
            });
            return false;
        });

        $("#coupon").click(function () {
            var model = {};
            //lấy ma giam gia
            model.Ma = $("#MaGiamGia").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddCoupon", "GioHang")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    alert(data.Message);
                    if (data.GiaTri != 0) {

                        var tienTra = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(@tongTienThanhToan - @tongTienThanhToan* data.GiaTri);
                        var tienGiam = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(@tongTienThanhToan* data.GiaTri);
                        $('#tienGiamGia').text(tienGiam);
                        $('#tienTong').text(tienTra);
                    }
                },
                error: function () {
                    alert("Bạn chưa đăng nhập hoặc mã giảm giá không hợp lệ");
                }
            });
            return false;
        });


    });
    </script>
}